# A sample Gemfile
source "https://rubygems.org"

gem 'data_mapper'
gem 'dm-postgres-adapter'
gem "sinatra"

group :test, :development do
  gem "rspec"
  gem "capybara"
  gem "pry"
  gem "launch"
  gem "rspec-sinatra"
  gem "database_cleaner"
end
