# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'

group :test, :development do
  gem "pry"
  gem "rspec"
  gem 'rspec-sinatra'
  gem "capybara"
  gem "database_cleaner"
end
